In [4]:
import pandas as pd, numpy as np
df = pd.read_csv("C:\dev\cardio-risk\data\extention of Z-Alizadeh sani dataset.csv")
print(df.shape)
print("missing values:", df.isna().sum().sum())
df.head()

(303, 59)
missing values: 0

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
C:\Users\msrpc\AppData\Local\Temp\ipykernel_38792\2379804855.py:2: SyntaxWarning: invalid escape sequence '\d'
  df = pd.read_csv("C:\dev\cardio-risk\data\extention of Z-Alizadeh sani dataset.csv")

,Age,Weight,Length,Sex,BMI,DM,HTN,Current Smoker,EX-Smoker,FH,...,Lymph,Neut,PLT,EF-TTE,Region RWMA,VHD,LAD,LCX,RCA,Cath
0,53,90,175,Male,29.387755,0,1,1,0,0,...,39,52,261,50,0,N,Stenotic,Normal,Stenotic,CAD
1,67,70,157,Fmale,28.398718,0,1,0,0,0,...,38,55,165,40,4,N,Stenotic,Stenotic,Normal,CAD
2,54,54,164,Male,20.077335,0,0,1,0,0,...,38,60,230,40,2,mild,Stenotic,Normal,Normal,CAD
3,66,67,158,Fmale,26.838648,0,1,0,0,0,...,18,72,742,55,0,Severe,Normal,Normal,Normal,Normal
4,50,87,153,Fmale,37.165193,0,1,0,0,0,...,55,39,274,50,0,Severe,Normal,Normal,Normal,Normal

In [5]:
print(df.dtypes.value_counts())
print()
for c in df.select_dtypes(exclude="number").columns:
    print(c, df[c].unique().tolist())

int64      29
str        25
float64     5
Name: count, dtype: int64

Sex ['Male', 'Fmale']
Obesity ['Y', 'N']
CRF ['N', 'Y']
CVA ['N', 'Y']
Airway disease ['N', 'Y']
Thyroid Disease ['N', 'Y']
CHF ['N', 'Y']
DLP ['Y', 'N']
Weak Peripheral Pulse ['N', 'Y']
Lung rales ['N', 'Y']
Systolic Murmur ['N', 'Y']
Diastolic Murmur ['N', 'Y']
Dyspnea ['N', 'Y']
Atypical ['N', 'Y']
Nonanginal ['N', 'Y']
Exertional CP ['N']
LowTH Ang ['N', 'Y']
LVH ['N', 'Y']
Poor R Progression ['N', 'Y']
BBB ['N', 'LBBB', 'RBBB']
VHD ['N', 'mild', 'Severe', 'Moderate']
LAD ['Stenotic', 'Normal']
LCX ['Normal', 'Stenotic']
RCA ['Stenotic', 'Normal']
Cath ['CAD', 'Normal']

In [6]:
for c in ["Cath", "LAD", "LCX", "RCA"]:
    print(c, df[c].value_counts().to_dict())

Cath {'CAD': 216, 'Normal': 87}
LAD {'Stenotic': 177, 'Normal': 126}
LCX {'Normal': 184, 'Stenotic': 119}
RCA {'Normal': 189, 'Stenotic': 114}

In [7]:
for c in ["Cath", "LAD", "LCX", "RCA"]:
    print(c, df[c].value_counts().to_dict())

Cath {'CAD': 216, 'Normal': 87}
LAD {'Stenotic': 177, 'Normal': 126}
LCX {'Normal': 184, 'Stenotic': 119}
RCA {'Normal': 189, 'Stenotic': 114}

In [8]:
df.describe().T[["min", "mean", "max"]]

                            min         mean           max
Age                   30.000000    58.897690     86.000000
Weight                48.000000    73.831683    120.000000
Length               140.000000   164.716172    188.000000
BMI                   18.115413    27.248339     40.900658
DM                     0.000000     0.297030      1.000000
HTN                    0.000000     0.590759      1.000000
Current Smoker         0.000000     0.207921      1.000000
EX-Smoker              0.000000     0.033003      1.000000
FH                     0.000000     0.158416      1.000000
BP                    90.000000   129.554455    190.000000
PR                    50.000000    75.141914    110.000000
Edema                  0.000000     0.039604      1.000000
Typical Chest Pain     0.000000     0.541254      1.000000
Function Class         0.000000     0.663366      3.000000
Q Wave                 0.000000     0.052805      1.000000
St Elevation           0.000000     0.046205      1.000000
St Depression          0.000000     0.234323      1.000000
Tinversion             0.000000     0.297030      1.000000
FBS                   62.000000   119.184818    400.000000
CR                     0.500000     1.055611      2.200000
TG                    37.000000   150.343234   1050.000000
LDL                   18.000000   104.643564    232.000000
HDL                   15.900000    40.233993    111.000000
BUN                    6.000000    17.501650     52.000000
ESR                    1.000000    19.462046     90.000000
HB                     8.900000    13.153465     17.600000
K                      3.000000     4.230693      6.600000
Na                   128.000000   140.996700    156.000000
WBC                 3700.000000  7562.046205  18000.000000
Lymph                  7.000000    32.399340     60.000000
Neut                  32.000000    60.148515     89.000000
PLT                   25.000000   221.488449    742.000000
EF-TTE                15.000000    47.231023     60.000000
Region RWMA            0.000000     0.620462      4.000000

In [9]:
df.describe().T[["min", "mean", "max"]]

                            min         mean           max
Age                   30.000000    58.897690     86.000000
Weight                48.000000    73.831683    120.000000
Length               140.000000   164.716172    188.000000
BMI                   18.115413    27.248339     40.900658
DM                     0.000000     0.297030      1.000000
HTN                    0.000000     0.590759      1.000000
Current Smoker         0.000000     0.207921      1.000000
EX-Smoker              0.000000     0.033003      1.000000
FH                     0.000000     0.158416      1.000000
BP                    90.000000   129.554455    190.000000
PR                    50.000000    75.141914    110.000000
Edema                  0.000000     0.039604      1.000000
Typical Chest Pain     0.000000     0.541254      1.000000
Function Class         0.000000     0.663366      3.000000
Q Wave                 0.000000     0.052805      1.000000
St Elevation           0.000000     0.046205      1.000000
St Depression          0.000000     0.234323      1.000000
Tinversion             0.000000     0.297030      1.000000
FBS                   62.000000   119.184818    400.000000
CR                     0.500000     1.055611      2.200000
TG                    37.000000   150.343234   1050.000000
LDL                   18.000000   104.643564    232.000000
HDL                   15.900000    40.233993    111.000000
BUN                    6.000000    17.501650     52.000000
ESR                    1.000000    19.462046     90.000000
HB                     8.900000    13.153465     17.600000
K                      3.000000     4.230693      6.600000
Na                   128.000000   140.996700    156.000000
WBC                 3700.000000  7562.046205  18000.000000
Lymph                  7.000000    32.399340     60.000000
Neut                  32.000000    60.148515     89.000000
PLT                   25.000000   221.488449    742.000000
EF-TTE                15.000000    47.231023     60.000000
Region RWMA            0.000000     0.620462      4.000000

In [10]:
n = (df[["LAD","LCX","RCA"]] == "Stenotic").sum(axis=1)
print(n.value_counts().sort_index())

0    86
1    87
2    67
3    63
Name: count, dtype: int64

In [11]:
d = df.copy()
d["CAD"] = (d["Cath"] == "CAD").astype(int)
corr = d.select_dtypes("number").corr()["CAD"].drop("CAD").sort_values(key=abs, ascending=False)
print(corr.head(12))

Typical Chest Pain    0.542967
Age                   0.357247
Region RWMA           0.316011
HTN                   0.287761
DM                    0.252897
BP                    0.237762
Tinversion            0.236933
EF-TTE               -0.234009
FBS                   0.205553
K                     0.181320
ESR                   0.178447
PR                    0.168366
Name: CAD, dtype: float64